name: test
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: go mod tidy
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: Build
        run: go build
      - name: Test
        run: go test
